### ISSUE TITLE
Helm chart does not work with readonly filesystem

### ISSUE THREAD

**Issue by yncyrydybyl** [nordeck/matrix-poll#22]
**Describe the bug**

The helm chart set the root file system to read only. But when starting off it wants to write cache-files.
I did a work around like https://github.com/nordeck/matrix-poll/compare/main...yncyrydybyl:matrix-poll:main

**Environment:**
I did that in an openshift cluster.

**Comment by dhenneke** [comment]
We set the writable folders as volumes in the [Dockerfile](https://github.com/nordeck/matrix-widget-toolkit/blob/10af1d9bd7fc5f8b2d3999d04f00d6ffb678e621/containers/widget-server/Dockerfile#L31). At least Docker and a containerd-based Kubernetes automatically creates temporary volumes for those folders. But we didn't tested it with OpenShift yet.

We could explicitly add `emptyDir` volumes for the required folders so CRI-O should also work.
